In [33]:
import tensorflow as tf
from transformers import BertTokenizer, TFBertModel

In [44]:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = TFBertModel.from_pretrained('bert-base-uncased')
input_ids = tf.constant(tokenizer.encode("it", add_special_tokens=False))[None, :]  # Batch size 1
outputs = model(input_ids)
last_hidden_states = outputs[0]  # The last hidden-state is the first element of the output tuple

In [45]:
last_hidden_states

<tf.Tensor: shape=(1, 1, 768), dtype=float32, numpy=
array([[[-6.23281360e-01,  3.83339018e-01,  5.75116016e-02,
         -6.14386141e-01,  3.85241508e-01, -3.16393226e-01,
          4.12926346e-01,  6.51225805e-01, -8.20477724e-01,
         -5.09270668e-01, -6.36992216e-01,  1.91643611e-01,
          3.60462368e-01,  1.81947276e-01, -2.50594258e-01,
          6.66517556e-01,  9.57601666e-02, -3.37035507e-01,
          5.38950145e-01, -4.84423280e-01, -3.03326398e-01,
         -3.84762675e-01,  9.54563618e-01,  5.13694525e-01,
          1.45950988e-01, -9.41169918e-01,  5.99790096e-01,
          1.09998554e-01, -3.99788134e-02,  2.81148285e-01,
          2.75594354e-01, -4.18485850e-01,  3.55274618e-01,
          3.89629751e-02, -4.89633501e-01,  2.47332230e-01,
          5.74592233e-01, -3.48188728e-03, -2.14060888e-01,
          7.40780532e-01, -6.07819036e-02, -1.79470882e-01,
          1.54080108e-01,  1.76173925e-01,  6.96245551e-01,
          6.96180999e-01, -5.82594097e-01,  4.1

In [48]:
from bert_serving.client import BertClient
bc = BertClient()
bc.encode(['First do do it'])

array([[ 2.23056853e-01,  5.69794953e-01, -3.45069975e-01,
        -5.09464443e-01, -2.76529402e-01, -2.01213375e-01,
         4.16144729e-01,  2.82843173e-01,  3.94355923e-01,
        -8.53750169e-01,  2.03142166e-01, -1.51816428e-01,
        -2.56308347e-01, -1.97617814e-01, -1.03803873e+00,
         3.38271111e-01, -3.50192696e-01, -1.72289208e-01,
         1.42426878e-01,  6.12719238e-01, -7.47300833e-02,
         2.22969234e-01, -1.55262217e-01,  3.16913873e-01,
         1.20222352e-01, -4.92642373e-01, -1.56273380e-01,
        -3.05320144e-01, -4.82751608e-01,  4.19525541e-02,
         3.89784425e-01, -2.56538570e-01, -9.81126651e-02,
        -2.99677104e-02, -9.70980600e-02,  4.81054634e-02,
         2.35864639e-01,  2.93146282e-01, -4.98622626e-01,
         2.97991902e-01, -2.40668610e-01, -3.73448610e-01,
         7.68290907e-02, -6.83053315e-01, -2.53883183e-01,
        -8.64875019e-01,  1.85022756e-01, -1.62515447e-01,
        -1.73653662e-01, -6.87008560e-01, -9.68003035e-0

In [49]:
import tensorflow as tf
from transformers import BertTokenizer, TFBertForSequenceClassification

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = TFBertForSequenceClassification.from_pretrained('bert-base-uncased')
input_ids = tf.constant(tokenizer.encode("Hello, my dog is cute", add_special_tokens=True))[None, :]  # Batch size 1
outputs = model(input_ids)
logits = outputs[0]

In [50]:
logits

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[-0.11136226,  0.47374606]], dtype=float32)>